/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.TrainService;
import org.example.services.UserBookingService;
import org.example.utils.userServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {
    public static void main(String[] args) {
        System.out.println("IRCTC Running...");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;

        try {
            userBookingService = new UserBookingService();
        } catch(IOException e){
            System.out.println("Something went wrong!");
            return;
        }

        while(option!=7){
            System.out.println("Choose Option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Exit");
            option = sc.nextInt();
            Train trainSelectedForBooking = new Train();

            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignup = sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignup = sc.next();
                    User userToSignup = new User(nameToSignup, passwordToSignup,
                            userServiceUtil.hashPassword(passwordToSignup),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signup(userToSignup);
                    break;

                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = sc.next();
                    System.out.println("Enter the password to Login");
                    String passwordToLogin = sc.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin,
                            userServiceUtil.hashPassword(passwordToLogin),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                    }catch(IOException e){
                        return;
                    }

                case 3:
                    System.out.println("Fetch Bookings");
                    userBookingService.fetchBookings();
                    break;

                case 4:
                    System.out.println("Type your source station");
                    String source = sc.next();
                    System.out.println("Type your destination station");
                    String destination = sc.next();
                    List<Train> trains = userBookingService.getTrains(source, destination);
                    int index = 1;
                    for(Train t: trains){
                        System.out.println(index + " Train id: "+t.getTrainId());
                        for(Map.Entry<String, String>entry: t.getStationsTime().entrySet()){
                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("select a train by typing 1,2,3....");
                    trainSelectedForBooking = trains.get(sc.nextInt());
                    break;

                case 5:
                    System.out.println("select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for(List<Integer> row : seats){
                        for(Integer val:row){
                            System.out.println(val +" ");
                        }
                        System.out.println();
                    }
                    System.out.println("select the seat using row and column");
                    System.out.println("Enter the row");
                    int row = sc.nextInt();
                    System.out.println("Enter the column");
                    int col = sc.nextInt();
                    System.out.println("Booking your seat......");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);

                    if(booked.equals(Boolean.TRUE)) System.out.println("Booked!");
                    else System.out.println("Failed!");

                    break;

                default:
                    break;

            }
        }
    }
}
