/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.utils.userServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {
    public static void main(String[] args) {
        System.out.println("IRCTC Running...");
        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;

        try {
            userBookingService = new UserBookingService();
        } catch(IOException e){
            System.out.println("Something went wrong!");
            return;
        }

        while(option!=7){
            System.out.println("Choose Option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Exit");
            option = sc.nextInt();

            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignup = sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignup = sc.next();
                    User userToSignup = new User(nameToSignup, passwordToSignup,
                            userServiceUtil.hashPassword(passwordToSignup),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signup(userToSignup);
                    break;

                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = sc.next();
                    System.out.println("Enter the password to Login");
                    String passwordToLogin = sc.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin,
                            userServiceUtil.hashPassword(passwordToLogin),
                            new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                    }catch(IOException e){
                        return;
                    }

                case 3:
                    System.out.println("Fetch Bookings");
                    userBookingService.fetchBookings();
                    break;

                case 4:

            }
        }
    }
}
